<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "myleaflet"
 *
 * Auto generated by Extension Builder 2019-12-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'MyLeaflet',
    'description' => 'Leaflet / OpenStreetMap for tt_address data with radial search and categories. No registration and no API-keys necessary.',
    'category' => 'plugin',
    'author' => 'Joachim Ruhs',
    'author_email' => 'postmaster@joachim-ruhs.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.6.2',
    'constraints' => [
        'depends' => [
            'typo3' => '11.4.0-12.5.99',
			'tt_address' => '7.0.0-7.1.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ]
];
