<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "myleaflet"
 *
 * Auto generated by Extension Builder 2019-12-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'MyLeaflet',
    'description' => 'Leaflet / OpenStreetMap for tt_address data with radial search and categories. No registration and no API-keys necessary.',
    'category' => 'plugin',
    'author' => 'Joachim Ruhs',
    'author_email' => 'postmaster@joachim-ruhs.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.7.3',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.8-10.4.99',
			'tt_address' => '4.0.0-5.9.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
