categories:
  MySet:
    label: 'Myleaflet'
  MySet.templates:
    label: 'Templates'
    parent: MySet
  MySet.layout:
    label: 'Layout'
    parent: MySet
  MySet.pages:
    label: 'Pages'
    parent: MySet
  MySet.options:
    label: 'Options'
    parent: MySet

settings:
#  plugin.tx_myleaflet.view.templateRootPath:
#  MySet.templateRootPath:
  plugin.tx_myleaflet.view.templateRootPath:
    label: 'Page template path'
    category: MySet.templates
    description: 'Path to templates root'
    type: string
    default: 'EXT:myleaflet/Resources/Private/Templates/'

#  MySet.partialRootPath:
  plugin.tx_myleaflet.view.partialRootPath:
    label: 'Partials'
    category: MySet.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:myleaflet/Resources/Private/Partials/'
#  MySet.layoutRootPath:
  plugin.tx_myleaflet.view.layoutRootPath:
    label: 'Layouts'
    category: MySet.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:myleaflet/Resources/Private/Layouts/'

  plugin.tx_myleaflet.view.includejQueryCore:
    label: 'IncludejQueryCore'
    category: MySet.templates
    description: 'IncludejQueryCore [0|1]'
    type: bool
    default: 0
  plugin.tx_myleaflet.view.jQueryFile:
    label: 'jQueryFile'
    category: MySet.templates
    description: 'jQuery file'
    type: string
    default: 'EXT:myleaflet/Resources/Public/JavaScript/jquery-3.5.1.min.js'
  plugin.tx_myleaflet.view.cssFile:
    label: 'cssFile'
    category: MySet.templates
    description: 'cssFile'
    type: string
    default: 'EXT:myleaflet/Resources/Public/CSS/myleaflet.css'



#  MySet.storagePid:
  plugin.tx_myleaflet.persistence.storagePid:
    label: 'Default storage PID'
    category: MySet.pages
    description: 'Folder that stores all data'
    type: page
    default: 0
  plugin.tx_myleaflet.settings.detailsPageId:
    label: 'details pageId'
    category: MySet.options
    description: 'The page uid of the details view'
    type: int
    default: 0
  plugin.tx_myleaflet.settings.resultLimit:
    label: 'result limit'
    category: MySet.options
    description: 'The limit of results'
    type: int
    default: 300
  plugin.tx_myleaflet.settings.initialMapCoordinates:
    label: 'initial map coordinates'
    category: MySet.options
    description: 'The initial coordinates of the map'
    type: string
    default: 48,8
  plugin.tx_myleaflet.settings.categorySelectMode:
    label: 'Category select mode: [AND|OR] Default OR'
    category: MySet.options
    description: 'Category select mode: [AND|OR] Default OR'
    type: string
    default: OR
  plugin.tx_myleaflet.settings.enableMarkerClusterer:
    label: 'enable marker clusterer'
    category: MySet.options
    description: 'Enable the marker clusterer'
    type: bool
    default: 0
  plugin.tx_myleaflet.settings.defaultIcon:
    label: 'default icon'
    category: MySet.options
    description: 'default marker icon'
    type: string
    default: ''
  plugin.tx_myleaflet.settings.defaultLanguageUid:
    label: 'default language uid'
    category: MySet.options
    description: 'Default language Uid'
    type: string
    default: ''

